export const UPDATE_USER = "UPDATE_USER";
export const LIST_COURSES = "LIST_COURSES";
export const LIST_USER_COURSES = "LIST_USER_COURSES";

// getters
export const GETTER_PREMISSION = "GETTER_PREMISSION";
